[package]
name = "macaw"
version = "0.1.0"
authors = ["Tucker Lein <self@tuckerle.in>"]
edition = "2018"
license = "MIT"

[workspace]
members = ["crates/*"]

[dependencies]
macaw_internal = {path = "crates/macaw_internal", version = "0.1.0" }

[[example]]
name = "hello_world"
