[package]
name = "kiln"
version = "0.1.0"
authors = ["Tucker Lein <self@tuckerle.in>"]
edition = "2018"
license = "MIT"

[workspace]
members = ["crates/*"]

[dependencies]
kiln_internal = {path = "crates/kiln_internal", version = "0.1.0" }

[[example]]
name = "hello_world"
