[package]
name = "kiln_editor"
version = "0.1.0"
authors = ["Tucker Lein <self@tuckerle.in>"]
edition = "2018"
license = "MIT"

[dependencies]
# kiln
kiln_data = { path = "../kiln_data", version = "0.1.0" }
